src/block.rs
To allow minimal changes in softwares to be compatible with both bitcoin and elements, would be great to have same field name for Block and BlockHeader.
As an example, see https://github.com/romanz/electrs/compare/master...greenaddress:elements_cond_compile?expand=1
to allow conditional compilation on elements
=> Use same struct field name as in rust-bitcoin

.travis.yml, Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/transaction.rs
To more closely match Elements, and to give users a way to refer to an outpoint independently of its use in an input.
=> Move `has_issuance` and `is_pegin` fields from OutPoint to TxIn

src/lib.rs
Because `elements::transaction` is private, the `AssetIssuance` struct cannot be accessed without this.
=> Export AssetIssuance

Cargo.toml, src/address.rs, src/blech32.rs, src/lib.rs
So I ported the blech32 code from Elements, but I seem to have some nit somewhere in the checksum code. Still figuring out.
=> Add Address type

Cargo.toml
The effect of this is only to increase the rust-secp version.
=> increase bitcoin dependency to 0.20

src/fast_merkle_root.rs, src/issuance.rs, src/lib.rs, src/transaction.rs
Based on Elements' [ComputeFastMerkleRoot](https://github.com/ElementsProject/elements/blob/master/src/primitives/txwitness.cpp#L50).
=> Add fast_merkle_root and AssetId type

src/block.rs, src/dynafed.rs
The Rust enum stuff is all fancy and such, but it's often a real pain in the ass to either just check which of the vairants is used or to get a field out if you already know what the variant is.
=> Add some inspector methods to dynafed::Params + support root calculation

Cargo.toml, src/lib.rs
We use the rust-bitcoin types. I know we should in the long term move away from that, but for now we still have several of the types that we reuse.
=> Export bitcoin dependency

Cargo.toml, src/dynafed.rs
Sorry, I should have noticed this was missing while reviewing the PR that added the elided_root field. There are getters for all the other fields, so we should probably have this one. I already bumped into missing this one.
=> Add Params::elided_root and Params::into_compact

Cargo.toml, src/address.rs, src/block.rs, src/encode.rs, src/transaction.rs
Forgot quite some :see_no_evil: .
=> Use more new Bitcoin hashtypes

src/confidential.rs, src/encode.rs, src/issuance.rs, src/transaction.rs
Follows on https://github.com/ElementsProject/rust-elements/pull/45.
The current inner type is just plain wrong. It's `sha256::Midstate` in theory.
=> Use AssetId as inner type for confidential::Asset

src/confidential.rs, src/encode.rs, src/transaction.rs
Solves https://github.com/ElementsProject/rust-elements/issues/18: enforce correct commitment prefixes.
Also replaces the `confidential::Nonce` inner value with `[u8; 32]` because it's not a `sha256d::Hash`. I'm not sure if this will cause any problem anywhere because they are not displayed the same way.
Plus some other improvements.
=> Confidential improvements

src/issuance.rs
To match the one found on other hash types.
=> Add AssetId::from_slice() convenience method

Cargo.toml, src/issuance.rs, src/lib.rs
Annoyingly this takes 2 extra dependencies. I made them optional, but default.
=> Add support for hashing JSON asset contract

Cargo.toml, src/address.rs, src/lib.rs, src/slip77.rs
An implementation of https://github.com/satoshilabs/slips/blob/master/slip-0077.md that is compatible with Elements Core and libwally.
=> Add SLIP-0077

.travis.yml, Cargo.toml, src/block.rs, src/issuance.rs, src/transaction.rs
* increase bitcoin_hashes dep accordingly
* remove BitcoinHash and use block_hash for block and header
* ~~remove std Error impl since MSVR increased and it's not necessary anymore~~
* ~~run cargo fmt, should have been a separate commit~~
* use instrunctions() iterator instead of iter(false)
* pin cc dep to 1.0.41 for travis 1.0.29 build
* removes, export RUSTFLAGS='-Clink-arg=-fuse-ld=gold' seems no longer necessary
~~Made several attempts to fix CI build with rust version 1.29.0 however it breaks trying to use cc dep `1.0.60` but I didn't find a way to use a lower version, any idea?~~
=> Increase bitcoin dep to 0.25.0

src/encode.rs, src/endian.rs, src/lib.rs, src/script.rs, src/sighash.rs, src/transaction.rs
Builds on top of #59. Will rebase after that is merged. Let me if you any ideas about how to quickly generate test vectors.
=> Add functionality to create sighash(legacy + segwit)

Cargo.toml, src/address.rs, src/blech32.rs, src/block.rs, src/confidential.rs, src/dynafed.rs, src/encode.rs, src/hash_types.rs, src/internal_macros.rs, src/issuance.rs, src/lib.rs, src/script.rs, src/sighash.rs, src/slip77.rs, src/transaction.rs
This is the part of PR https://github.com/ElementsProject/rust-elements/pull/70 which should be less controversial.
When splitting up that PR and going through @sanket1729's review I noticed that we had broken the serde implementations of `Value`, `Asset` and `Nonce` (and I found [this](https://github.com/ElementsProject/rust-secp256k1-zkp/pull/10) (our) bug in rust-secp256k1-zkp). 
This also made me realise that, by delegating to said library when implementing serde on our types, we had introduced breaking changes. I've documented the original serde implementations with the tests in https://github.com/ElementsProject/rust-elements/commit/1c53b177c3e56c21836fa3f89bb4b4f2da0689ef, to be able to highlight the changes introduced in https://github.com/ElementsProject/rust-elements/commit/516ac …
=> Model Value, Asset and Nonce confidential variants using secp256k1-zkp types

Cargo.toml
- Change the structure of several Transaction primitives to use
native secp types.
- Support for pset
- Support for transaction blinding and creating confidential
transactions
- Support for unblinding transactions #78
=> Release 0.17

src/blind.rs, src/lib.rs, src/pset/mod.rs
BlindError, UnblindError and PsetBlindError are used by public
functions but are not exported.
However I am not sure those were meant to be exposed.
Perhaps they should have been variants of already exported errors.
=> Export blind errors

src/script.rs
Similarly to rust-bitcoin's `Script` (via the impl_index_newtype macro: https://github.com/rust-bitcoin/rust-bitcoin/blob/0.27.1/src/internal_macros.rs#L103-L110)
=> Implement Index<usize> for Script

src/pset/map/global.rs
From https://doc.rust-lang.org/std/vec/struct.Vec.html#method.dedup 
Removes consecutive repeated elements in the vector according to the PartialEq trait implementation.
If the vector is sorted, this removes all duplicates.
=> Use sort before dedup to achieve uniqueness

src/block.rs
It turns out really painful to get the current parameters from a header.
=> Add dynafed getter helpers on BlockHeader

src/dynafed.rs
The fedpegscript and witness values are Vec<u8> and displayed as arrays
of integers. This implementation changes that to show hex strings for
them instead.
=> Improve the dynafed::Params fmt::Debug implementation

Cargo.toml, src/block.rs, src/dynafed.rs
close #113 
The number of fields in the Params struct is wrong, this causes an error in roundtrip as shown in the included tests.
Strangely enough, this looks to happen only for binary encoding
=> Fix BlockHeader roundtrip bug on serde binary encoding

src/address.rs, src/encode.rs, src/lib.rs, src/schnorr.rs, src/sighash.rs, src/taproot.rs, src/transaction.rs, tests/taproot.rs
Commits 86979bc518e781ed8c9bf19412652792c739fa5e and 16ba676ab8157bc823b08e6d5bdb5e1bbbdc5f26 don't compile. They are only separated for review aid. These commits have code that is copied from rust-bitcoin, and the subsequent commits make the elements specific changes which should be easy to review.
After this is ready for merge, I will squash the non-compiling commits to have a good history.
The last commit has integration tests for sighash/taproot tests for elements
=> Taproot Support

.github/workflows/rust.yml, src/issuance.rs
Tests for vout os serialized correctly in the correct byte order. vout = 0 would result in the same ordering for LE and BE
=> Add test vector for issuance with previous utxo with vout = 1

Cargo.toml, examples/pset_blind_coinjoin.rs, examples/raw_blind.rs, src/blind.rs, src/confidential.rs, src/encode.rs, src/pset/map/input.rs, src/pset/map/mod.rs, src/pset/map/output.rs, src/pset/mod.rs, src/pset/serialize.rs, src/schnorr.rs, src/script.rs, src/sighash.rs, src/slip77.rs, src/taproot.rs, tests/taproot.rs
These work directly with elements 23.0(24.0?) after it has been released.
There are no changes to elements specific proprietary fields, only main
bitcoin psbt fields.
Most of this is just copy pasting code from rust-bitcoin and making it work :) . For reference: 
https://github.com/bitcoin/bips/blob/master/bip-0371.mediawiki. 
Unfortunately, this is the only supporting implementation. So, there are no test vectors to check against.
=> Add taproot psbt fields according to BIP371

CHANGELOG.md, Cargo.toml
Dependency upgrade and taproot support implemented in #121. Please review that before making a release. 
This PR is now only has a single commit with the release. 
Fixes #112
=> Update dependancies and release 0.19

src/block.rs, src/transaction.rs
To match the changes introduced in https://github.com/rust-bitcoin/rust-bitcoin/pull/861.
This allows using unified code with the same methods for both `elements::{Transaction,Block}` and `bitcoin::{Transaction,Block}` (behind different features), without triggering rust-bitcoin's deprecation warnings for the `get_`-prefixed methods.
Note that there are other instances of `get_`-prefixed methods in the rust-elements codebase. I only updated the ones needed for compatibility with the changes made in rust-bitcoin.
=> Deprecate get_ prefix for Block and Transaction methods

src/pset/mod.rs, src/transaction.rs
These are the same values from rust-bitcoin. Makes it easy to create
these structures downstream. Right now, we need to specify all feilds
=> Add some default impls

Cargo.toml, fuzz/Cargo.toml, src/address.rs, src/blind.rs, src/block.rs, src/confidential.rs, src/dynafed.rs, src/encode.rs, src/internal_macros.rs, src/issuance.rs, src/lib.rs, src/pset/error.rs, src/pset/map/global.rs, src/pset/map/input.rs, src/pset/map/mod.rs, src/pset/map/output.rs, src/pset/mod.rs, src/pset/raw.rs, src/pset/serialize.rs, src/schnorr.rs, src/script.rs, src/serde_utils.rs, src/sighash.rs, src/slip77.rs, src/taproot.rs, src/transaction.rs
Fixes #132 
I went through the steps [to transition to a new edition](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html)
The only fixes necessary were removing `$crate::` in the trait bounds of `impl_consensus_encoding` macro, and then fixing a few issues that didn't appear with default features.
=> upgrade to 2018 edition

src/transaction.rs
Noticed while reading that a malformed pegin witness could actually make our code panic.
=> Avoid panic malformed pegin

src/transaction.rs
This is a breaking change only in the field of the asset. I thought it made more sense like that, but if we prefer to not make breaking changes, the utility methods could also be added without the field change.
=> Add utility methods to create pegin witnesses

src/blind.rs, src/lib.rs
So that the traits methods can be used downstream.
=> Export Blind*Proofs traits

src/encode.rs, src/error.rs, src/lib.rs, src/locktime.rs, src/parse.rs, src/pset/map/global.rs, src/pset/map/input.rs, src/pset/mod.rs, src/pset/serialize.rs, src/sighash.rs, src/transaction.rs, tests/taproot.rs
The PSET stuff I'm a little uncertain about -- PSBT2 brings new locktime logic in that doesn't exist in PSBT0. My new logic is essentially the same, except that while previously we would allow the user to specify invalid locktimes (since we just parsed a u32 with no further checking) now we don't.
I think, when we do this upstream in rust-bitcoin, we should probably introduce some helper methods into LockTime, because currently there are conversions from Time/Height into LockTime that feel misplaced.
Also, it is really unclear what the difference between LockTime and PackedLockTime is supposed to be, so I did my best to copy rust-bitcoin.
=> Introduce Sequence and LockTime from rust-bitcoin

src/error.rs, src/locktime.rs, src/transaction.rs
There is no `std` feature in rust-elements. This is a copy-and-paste error from rust-bitcoin.
=> Remove std feature gates

Cargo.toml, src/confidential.rs, src/transaction.rs
This haven't any consensuns meaning but it's useful to have transactions in ordered collections
~~depends on https://github.com/BlockstreamResearch/rust-secp256k1-zkp/pull/68~~ merged
~~draft because needs rust-secp256k1-zkp release https://github.com/BlockstreamResearch/rust-secp256k1-zkp/pull/70~~
=> Implement Ord for Transaction

src/transaction.rs
IMO these are different than f.e. the Default impls on TxOut etc, because these types actually in many actual production cases want to be set to the empty or none value. As opposed to Default on other types that only exist to aid in test scenarios or so to avoid having to set the fields.
=> Create explicit empty and null values for some types

Cargo.toml, contrib/test.sh, elementsd-tests/Cargo.toml, elementsd-tests/src/pset.rs, src/blech32.rs, src/pset/mod.rs, src/pset/str.rs
via standard trait Display and FromStr like it's done in rust-bitcoin PSBT.
Reuse rust-bitcoin base64 re-exported
=> Add to and from base64 string to pset

src/pset/mod.rs, src/pset/str.rs
Otherwise the pset decoding from string cannot be used downstream
fix #175
=> rename pset::str::Error to ParseError and expose it

contrib/test.sh, src/pset/elip100.rs, src/pset/mod.rs
as defined in https://github.com/ElementsProject/ELIPs/blob/main/elip-0100.mediawiki but considering proposed fixes in https://github.com/ElementsProject/ELIPs/pull/7
=> ELIP-0100 implementation

src/pset/elip100.rs
Missing from #182  otherwise there is no way to instantiate `AssetMetadata` and call `add_asset_metadata`
=> elip100: add missing AssetMetadata::new method

src/blind.rs
Fixes a typo in Value::blind doc
=> Updated doc for impl Value blind method - returns blinded value*

examples/pset_blind_coinjoin.rs, examples/raw_blind.rs, src/blind.rs, src/dynafed.rs, src/hex.rs, src/parse.rs, src/pset/elip100.rs, src/pset/error.rs, src/transaction.rs
examples: fix typos in docs
src: fix typos in docs
=> Fix: typos in docs

src/address.rs
To prevent any regression in address computation.
Should cover any standard script template combination with every network with or without a blinding key.
Tested also on rust-elements v0.23.0 https://github.com/RCasatta/rust-elements/tree/test_fixed_addresses_023
related https://github.com/ElementsProject/rust-elements/pull/188
=> add test against fixed addresses

src/dynafed.rs
Currently there is no way to construct the FullParams struct in a client app except for deserializing it or decoding it. This PR just adds a `new(...)` method so that this can be done.
=> Add public constructor for FullParams

contrib/test.sh, src/pset/map/input.rs
They were added in https://github.com/ElementsProject/elements/pull/1157
=> pset: input: add explicit amount and asset, and their proofs

src/pset/error.rs, src/pset/map/input.rs, src/pset/mod.rs
Added in https://github.com/ElementsProject/elements/pull/1157
=> pset: input: add blinded issuance flag

src/pset/map/input.rs, src/pset/map/output.rs, src/pset/mod.rs, src/pset/serialize.rs
Change corresponding to https://github.com/ElementsProject/elements/pull/1329
=> pset: add optional asset blinding factor to input and output

src/transaction.rs
It is possible to cause a panic by calling `TxIn::pegin_data` on a malformed pegin, which has 6 entries and the last one (which should be a Merkle proof of block inclusion) is too small to even have a blockhash in it.
On the actual chain this should not be possible because invalid pegin data would be rejected.
=> transaction: range-check pegin data when parsing

src/pset/elip100.rs
Following changes in https://github.com/ElementsProject/ELIPs/pull/17
=> pset: elip100: add and get token metadata

src/block.rs, src/encode.rs, src/ext.rs, src/lib.rs, src/pset/map/global.rs, src/pset/raw.rs, src/pset/serialize.rs
Following bitcoin versions change `io` with `bitcoin_io`, upgrading would then require changing also elements::Encodable to match.
Instead, we are re-implementing what is needed.
Makes #209 easier
=> Stop implementing elements::Encodable with bitcoin::Encodable

Cargo.toml, contrib/test.sh, elementsd-tests/Cargo.toml, elementsd-tests/src/lib.rs, src/address.rs, src/blech32/decode.rs, src/blech32/mod.rs, src/blind.rs, src/hash_types.rs, src/lib.rs, src/pset/error.rs, src/script.rs
https://github.com/ElementsProject/rust-elements/issues/208
```
fn consensus_encode<W: bitcoin::io::Write + ?Sized>(&self, e: W) -> Result<usize, crate::encode::Error> {}
fn consensus_decode<R: bitcoin::io::BufRead + ?Sized>(reader: &mut R) -> Result<Self, crate::encode::Error> {}
```
We went for not depending on bitcoin::Encodable instead
=> upgrade to bitcoin 0.32

src/address.rs
User code can already compare against AddressParams, but it seems easier to find a method to check if the address is liquid. Even tough is less general because you can't discriminate between elements and liquid testnet, most of the time wallets are interested only in the mainnet or not discrimination.
=> add `Address::is_liquid`

.github/workflows/rust.yml, contrib/test.sh, src/blind.rs, src/encode.rs, src/fast_merkle_root.rs, src/hash_types.rs, src/opcodes.rs, src/pset/map/input.rs, src/script.rs, src/taproot.rs
There is a new clippy/rustc nightly lint about having massive paragraphs as the first line of doccomments. The first line is treated specially and should be reasonably short.
=> docs: add a bunch of paragraph breaks.

src/transaction.rs
output amount and nonce discount must be weighted by the witness scaling factor as they form part of the base transaction, not the witness data 
see https://github.com/ElementsProject/elements/pull/1366
=> discount: fix weight calculation

contrib/test.sh, src/blech32/decode.rs, src/block.rs, src/confidential.rs, src/dynafed.rs, src/hex.rs, src/issuance.rs, src/serde_utils.rs, src/sighash.rs
Fixes clippy for the stable CI job, and pins libc to 0.2.163 for the rust 1.56.1 job
=> ci: fixes for rust stable clippy, and rust 1.56.1 compilation

src/transaction.rs
In #204 we included a lot of files for discountCT test cases, but one of the files was never tested (2in3out_tx.hex). This is just the testing of that file.
=> tx: discountct: add missing testcase from #204

elementsd-tests/src/pset.rs
In Elements 22 there was a change in the `createpsbt` RPC that causes our integration tests to fail. This is fixed by disabling blinding.
Patch by Leo Comandini, adapted by me to still work with 0.21, from https://github.com/ElementsProject/rust-elements/issues/214
Fixes #214
=> elementsd-tests: blind asset issuance based on node version

.github/workflows/rust.yml, Cargo.toml
=> Fix WASM build and add a job in CI

src/pset/elip101.rs, src/pset/map/input.rs
As it is done for pset outputs.
=> pset: input: insert non-pset proprietary keys

src/issuance.rs
This will allow constructing `AssetId` values like this:
```
const TESTNET_ASSET: elemets::AssetId = const_asset_id("144c654344aa716d6f3abcc1ca90e5641e4e2a7f633bc09fe3baf64585819a49");
/// Panics if the asset id string has wrong length or format
pub const fn const_asset_id(s: &str) -> elements::AssetId {
let mut data: [u8; 32] = hex_literal::decode::<32>(&[s.as_bytes()]);
let mut left = 0;
let mut right = data.len() - 1;
while left < right {
let tmp = data[left];
data[left] = data[right];
data[right] = tmp;
left += 1;
right -= 1;
}
elements::AssetId::from_inner(bitcoin::hashes::sha256::Midstate(data))
}
```
It's a bit of a hack because `hex_literal::decode` should not be used directly.
=> Make AssetId::from_inner a const function

src/pset/elip102.rs, src/pset/mod.rs
ELIP number was was changed from 101 to 102.
See discussion here https://github.com/ElementsProject/ELIPs/pull/20
=> elip102: rename from elip101

CHANGELOG.md, Cargo.toml
The elip rename is a breaking change, but it's highly likely we are the only one using it and a patch release would allow us to avoid the deps release dance
=> bump version 0.25.1 -> 0.25.2

src/dynafed.rs, src/transaction.rs
fix some minor issues in comments
=> chore: fix some minor issues in comments

src/blind.rs, src/lib.rs, src/pset/mod.rs
Right now we have:
* `Transaction::blind` returns abf, vbf and ephemeral private key
* `PartiallySignedTransaction::blind_non_last` returns abf and vbf
* `PartiallySignedTransaction::blind_last` returns nothing
This PR makes things more consistent and makes ephemeral keys more easily accessible.
It's a breaking change, but it's just augmenting the data, so it should be easy to handle downstream.
=> pset: blind: return ephemeral private key

CHANGELOG.md, Cargo-latest.lock, Cargo.toml, src/encode.rs, src/pset/error.rs, src/pset/mod.rs
I want to do the dtolnay "semver trick" where I release 0.25.3 which re-exports most of the types and traits from 0.26. This will make migration easier for users since they could use elements 0.25 and 0.26 in the same crate and have compatible types. In particular https://github.com/ElementsProject/elements-miniscript/pull/97 would compile without needing to update `simplicity` and `elements` at the same time.
However, when doing this I identified some gaps in the API which make this harder than it should be. See the commit messages for detailed justifications.
Also release 0.26.1 with these changes.
=> Release 0.26.1 with some minor API extensions
